export const languages = [
  { value: "C", label: "C" },
  { value: "C++", label: "C++" },
  { value: "Csharp", label: "C#" },
  { value: "CSS", label: "CSS" },
  { value: "Dart", label: "Dart" },
  { value: "Go", label: "Go" },
  { value: "HTML", label: "HTML" },
  { value: "Java", label: "Java" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "JSON", label: "JSON" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "Lua", label: "Lua" },
  { value: "Markdown", label: "Markdown" },
  { value: "Matlab", label: "Matlab" },
  { value: "MySQL", label: "MySQL" },
  { value: "Objective-C", label: "Objective-C" },
  { value: "Perl", label: "Perl" },
  { value: "PHP", label: "PHP" },
  { value: "PowerShell", label: "PowerShell" },
  { value: "Python", label: "Python" },
  { value: "R", label: "R" },
  { value: "Ruby", label: "Ruby" },
  { value: "Rust", label: "Rust" },
  { value: "Scala", label: "Scala" },
  {value: "SQLite", label: "SQLite"},
  { value: "Swift", label: "Swift" },
  { value: "Typescript", label: "TypeScript" },
  { value: "VBScript", label: "VBScript" },
  { value: "XML", label: "XML" },
  { value: "YAML", label: "YAML" },
]
